### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by Kantoborgy** [specify/specify7-docker#10]
![image](https://user-images.githubusercontent.com/28536681/117581048-68006d80-b0c0-11eb-8760-1f0792bff5b7.png)

**Comment by maxpatiiuk** [comment]
@kantobogy this should be fixed now for newly created docker instances.

To fix your existing container, run the following command in the terminal:
```bash
docker exec specify7-docker_mariadb_1 mysql -uroot -proot --database specify -e "UPDATE specifyuser SET Password='852ECA0808C42E62A3C8BB2E3095C3FDFABDEB4628E83F4A'";
```

This would reset the password for all users to `demouser` in the `specify7-docker_mariadb_1` Docker container

**Comment by maxpatiiuk** [comment]
@benanhalt It seems like Specify 7 user authentication isn't working when the password is saved in plain text in the database.

![Screenshot from 2021-05-09 21-01-29](https://user-images.githubusercontent.com/40512816/117582709-049c2d00-b10c-11eb-8077-1411e2bc988e.png)

In Specify 6, it would have gotten converted to `852ECA0808C42E62A3C8BB2E3095C3FDFABDEB4628E83F4A` automatically.

**Comment by Kantoborgy** [comment]
> @kantobogy this should be fixed now for newly created docker instances.
> 
> To fix your existing container, run the following command in the terminal:
> 
> ```shell
> docker exec specify7-docker_mariadb_1 mysql -uroot -proot --database specify -e "UPDATE specifyuser SET Password='852ECA0808C42E62A3C8BB2E3095C3FDFABDEB4628E83F4A'";
> ```
> 
> This would reset the password for all users to `demouser` in the `specify7-docker_mariadb_1` Docker container



> @kantobogy this should be fixed now for newly created docker instances.
> 
> To fix your existing container, run the following command in the terminal:
> 
> ```shell
> docker exec specify7-docker_mariadb_1 mysql -uroot -proot --database specify -e "UPDATE specifyuser SET Password='852ECA0808C42E62A3C8BB2E3095C3FDFABDEB4628E83F4A'";
> ```
> 
> This would reset the password for all users to `demouser` in the `specify7-docker_mariadb_1` Docker container



> @kantobogy this should be fixed now for newly created docker instances.
> 
> To fix your existing container, run the following command in the terminal:
> 
> ```shell
> docker exec specify7-docker_mariadb_1 mysql -uroot -proot --database specify -e "UPDATE specifyuser SET Password='852ECA0808C42E62A3C8BB2E3095C3FDFABDEB4628E83F4A'";
> ```
> 
> This would reset the password for all users to `demouser` in the `specify7-docker_mariadb_1` Docker container

**Comment by benanhalt** [comment]
@maxxxxxdlp It's bad practice to accept plain text passwords. In 6 it is not such a big deal because it has to operate on a local network. If 7 accepted plain text passwords, and someone's database leaked, then the encrypted passwords from the database could be used as plain text passwords to log into any account. It is better to do it the way you did in this issue. Set a user's password to a known encrypted password such as 'testuser' or 'demouser' and allow them to change it.
